velocity_controller_lqr_node:
  ros__parameters:

    #Path parameters
    odom_path: /nucleus/odom
    guidance_path: /guidance/los
    thrust_path: /thrust/wrench_input

    #LQR parameters

    q_surge: 75
    q_pitch: 175
    q_yaw: 175

    r_surge: 0.3
    r_pitch: 0.4
    r_yaw: 0.4

    i_surge: 0.3
    i_pitch: 0.4
    i_yaw: 0.3

    #Clamp parameter
    max_force: 99.5
