fixes:
  - "ros_ws/src/*/vortex-auv/acoustics/::"
  - "ros_ws/src/*/vortex-auv/auv_setup/::"
  - "ros_ws/src/*/vortex-auv/mission/::"
  - "ros_ws/src/*/vortex-auv/motion/::"


comment:
  layout: "header, diff, flags, components"

coverage:
  precision: 2
  round: down

ignore:
  - "**/*.ipynb"
  - docs
  - docker
  - binder
  - .github
  - .git
