dp_adapt_backstepping_controller:
  ros__parameters:
    control_topic: /thrust/wrench_input
    dp_reference_topic: /dp/reference
    odom_topic: /orca/odom
    pose_topic: /dvl/pose
    twist_topic: /dvl/twist
    K1 : [20.5, 15.5, 20.5, 1.2, 6.0, 2.5]
    K2 : [30.5, 25.5, 30.5, 2.6, 10.0, 6.5]
    r_b_bg : [0.01, 0.0, 0.02]
    adapt_gain : [0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8]
    d_gain : [0.3, 0.3, 0.45, 0.2, 0.7, 0.6]