# Parameters used for the DP-reference model
dp_rm:
  zeta_1: 1.0
  zeta_2: 1.0
  zeta_3: 1.0
  zeta_4: 1.0
  zeta_5: 1.0
  zeta_6: 1.0
  zeta_7: 1.0

  omega_1: 1.0
  omega_2: 1.0
  omega_3: 1.0
  omega_4: 1.0
  omega_5: 1.0
  omega_6: 1.0
  omega_7: 1.0
