version: '3.8'
services:

  auv:
    container_name: auv
    image: ghcr.io/vortexntnu/vortex-auv:development
    stdin_open: true
    tty: true
    network_mode: host

  auv-dev:
    container_name: auv-dev
    image: ghcr.io/vortexntnu/vortex-auv:development
    privileged: true
    volumes:
      - "../..:/vortex_ws/src"
      - "/dev:/dev"
    environment:
      DISPLAY: :0
    stdin_open: true
    tty: true
    network_mode: host
    entrypoint: ["/bin/bash", "-l"]
