# This file defines parameters specific to Gladlaks
#
# When looking at the AUV from above, the thruster placement is:   
#
#        front
#       |======|
#  |=7↗=|      |=0↖=|
#  |    |      |    |
#  | 6• |      | 1• |
#  |    |      |    |
#  |    |      |    |
#  | 5• |      | 2• |
#  |    |      |    |
#  |=4↖=|==||==|=3↗=|
#

physical:
  weight: 29.20     # kg
  buoyancy: 29.43   # kg
  displacement_m3: 0.02943
  center_of_mass: [26.3, 0.8, 6.0]        # mm (x,y,z)
  center_of_buoyancy: [25.9, 0.8, 48.3]   # mm (x,y,z)


propulsion:
  dofs:
    num: 6
    which:
      surge: true
      sway:  true
      heave: true
      roll:  true
      pitch: true
      yaw:   true
  thrusters:
    num: 8
    configuration_matrix:
      [[ 0.70711,  0.00000,  0.00000,  0.70711,  0.70711,  0.00000,  0.00000, 0.70711], # Surge
       [ 0.70711,  0.00000,  0.00000,  -0.70711, 0.70711,  0.00000,  0.00000,-0.70711], # Sway
       [ 0.00000,  1.00000,  1.00000,  0.00000,  0.00000,  1.00000,  1.00000, 0.00000], # Heave
       [ 0.00000, -0.22000, -0.22000,  0.00000,  0.00000,  0.22000,  0.22000, 0.00000], # Roll
       [ 0.06500, -0.24000,  0.24000,  0.06500,  0.06500,  0.24000, -0.24000, 0.06500], # Pitch 
       [ 0.32557,  0.00000,  0.00000,  0.32557,  -0.32557, 0.00000,  0.00000,-0.32557]] # Yaw

    rate_of_change:
      max: 1 # Maximum rate of change in newton per second for a thruster
    characteristics:  
      thrust:      [-34.5, -24.0, -12.9, -3.92, 0.00, 4.91, 12.6, 26.1, 35.5, 44.3] 
      pulse_width: [ 1100,  1192,  1292,  1400, 1500, 1600, 1676, 1780, 1840, 1900]
    map: [0, 1, 2, 3, 4, 5, 6, 7]  
    direction: [1, -1, 1, 1, -1, -1, 1, -1]
    offset: [80, 80, 80, 80, 80, 80, 80, 80] # Offset IN PWM!


controllers:
  dp:
    circleOfAcceptance: 0.10
    frequency: 40 # THIS SHOULD BE 40Hz for the controller to perform good. This is because the built in reference model will work 2x faster as if the controller ran at 20Hz
    velocity_gain: 3.5   #0.4
    position_gain: 30.5   #5.0
    attitude_gain: 1.3  #2.5
    integral_gain: 0.024 #0.3
  los_controller: # Note: Not loaded by the backstepping/pid controllers yet! Make sure to do this after tuning with dyn. reconf.
    PID:
      p: 25.0
      i: 0.0024
      d: 3.5
      sat: 3.0
    backstepping:
      c:  3.75
      k1: 45.0
      k2: 28.0
      k3: 10.5
  velocity_controller:
    P_gains: [20, 20, 20, 5, 5, 5]
    I_gains: [0, 0, 0, 0, 0, 0]
    D_gains: [0, 0, 0, 0, 0, 0]
    F_gains: [10, 15, 20, 5, 10, 5]
    integral_windup_limit: 5        # in newton
    setpoint_range: 1.5             # max distance from current point to setpoint
    max_output_ramp_rate: 1         # in newton per cycle
      
guidance:
  LOS:
    delta: 0.7
        
joystick:
  scaling:
    surge: 60
    sway: 60
    heave: 60
    roll: 30
    pitch: 30
    yaw: 30

battery:
  thresholds:
    warning: 14  # Volts
    critical: 13 # Volts
  logging:
    interval: 10   # Seconds
    path: "/sys/bus/i2c/drivers/ina3221x/1-0040/iio:device0/in_voltage0_input" # Path to monitor
    powersense_dev: "/dev/ttyUSB2"

temperature:
  logging:
    interval: 10    # Seconds
    temperature_template: "\d*\.\d*"
    zones:
      cpu: "CPU"
      gpu: "GPU"
      
i2c:
  address: 0x40
  bus: 8

pca9685:
  pwm:
    bits_per_period: 4095 
    frequency: 50.0
    frequency_measured: 50 # 51.6 is the former value, but we dont know why

