# This file defines parameters specific to Beluga
#
# When looking at the AUV from above, the thruster placement is:   
#
#        front
#       |======|
#  |=7↗=|      |=0↖=|
#  |    |      |    |
#  | 6• |      | 1• |
#  |    |      |    |
#  |    |      |    |
#  | 5• |      | 2• |
#  |    |      |    |
#  |=4↖=|==||==|=3↗=|
#

/**:
  ros__parameters:
    propulsion:
      dofs:
        num: 6
        which:
          surge: true
          sway:  true
          heave: true
          roll:  true
          pitch: true
          yaw:   true
      thrusters:
        num: 8
        min: -100
        max: 100
        configuration_matrix: #NED
          [ 0.70711,  0.00000,  0.00000,  0.70711,  0.70711,  0.00000,  0.00000,  0.70711, # Surge
          -0.70711,  0.00000,  0.00000,  0.70711, -0.70711,  0.00000,  0.00000,  0.70711, # Sway
           0.00000,  1.00000,  1.00000,  0.00000,  0.00000,  1.00000,  1.00000,  0.00000, # Heave
           0.01414,  0.15000,  0.15000, -0.01414,  0.01414, -0.15000, -0.15000, -0.01414, # Roll
           0.01414, -0.31000,  0.37500,  0.01414,  0.01414,  0.31000, -0.31000,  0.01414, # Pitch 
          -0.41720,  0.00000,  0.00000, -0.44901,  0.44901,  0.00000,  0.00000,  0.41720] # Yaw