# This file defines parameters specific to (Insert Name of New AUV).
#
# When looking at the AUV from above, the thruster placement is:   
#
#        front
#       |======|
#  |=7↗=|      |=0↖=|
#  |    |      |    |
#  | 6• |      | 1• |
#  |    |      |    |
#  |    |      |    |
#  | 5• |      | 2• |
#  |    |      |    |
#  |=4↖=|==||==|=3↗=|
#

/**:
  ros__parameters:
    propulsion:
      dofs:
        num: 6
      thrusters:
        num: 8
        min: -100
        max: 100
        configuration_matrix: #NED
          [ 0.70711,  0.00000,  0.00000,  0.70711,  0.70711,  0.00000,  0.00000,  0.70711,  # Surge
           -0.70711,  0.00000,  0.00000,  0.70711, -0.70711,  0.00000,  0.00000,  0.70711,  # Sway
            0.00000,  1.00000,  1.00000,  0.00000,  0.00000,  1.00000,  1.00000,  0.00000,  # Heave

            0.04243,  0.16500,  0.16500, -0.04243,  0.04243, -0.16500, -0.16500, -0.04243,  # Roll
            0.04243, -0.28500,  0.38000,  0.04243,  0.04243,  0.38000, -0.28500,  0.04243,  # Pitch 
           -0.42073,  0.00000,  0.00000, -0.47730,  0.47730,  0.00000,  0.00000,  0.42073 ] # Yaw
        rate_of_change:
          max: 1 # Maximum rate of change in newton per second for a thruster
        map:       [ 7,  6,  5,  4,  3,  2,  1,  0 ] # [ 0, 1, 2, 3, 4, 5, 6, 7 ]  
        direction: [ 1,  1,  1,  1,  1,  1,  1,  1 ]
        offset:    [ 80, 80, 80, 80, 80, 80, 80, 80 ] # Offset IN PWM -400 to 400 # Offset moves where the thrust is at rest
        thrust_range: [-0.7, 0.7] # range in percentage -1.0 to 1.0 # NOTE!: thrust_range moves with the offset, if the offset is too big e.g., ± ~400 the thrust range will go out of bounds 
