# This file defines parameters specific to (Insert Name of New AUV).
#
# When looking at the AUV from above, the thruster placement is:   
#
#        front
#       |======|
#  |=7↗=|      |=0↖=|
#  |    |      |    |
#  | 6• |      | 1• |
#  |    |      |    |
#  |    |      |    |
#  | 5• |      | 2• |
#  |    |      |    |
#  |=4↖=|==||==|=3↗=|
#

/**:
  ros__parameters:
    propulsion:
      dofs:
        num: 6
      thrusters:
        num: 8
        min: -100
        max: 100
        configuration_matrix: #NED
          [ 0.70711,  0.00000,  0.00000,  0.70711,  0.70711,  0.00000,  0.00000,  0.70711,  # Surge
           -0.70711,  0.00000,  0.00000,  0.70711, -0.70711,  0.00000,  0.00000,  0.70711,  # Sway
            0.00000,  1.00000,  1.00000,  0.00000,  0.00000,  1.00000,  1.00000,  0.00000,  # Heave

            0.04243,  0.16500,  0.16500, -0.04243,  0.04243, -0.16500, -0.16500, -0.04243,  # Roll
            0.04243, -0.28500,  0.38000,  0.04243,  0.04243,  0.38000, -0.28500,  0.04243,  # Pitch 
           -0.42073,  0.00000,  0.00000, -0.47730,  0.47730,  0.00000,  0.00000,  0.42073 ] # Yaw
        rate_of_change:
          max: 1 # Maximum rate of change in newton per second for a thruster
        
        thruster_to_pin_mapping: [7,  6,  5,  4,  3,  2,  1,  0] # I.e. if thruster_to_pin = [ 7,  6,  5,  4,  3,  2,  1,  0 ] then thruster 0 is pin 1 etc..
        thruster_direction: [1,  1,  1,  1,  1,  1,  1,  1]  # Disclose during thruster mapping (+/- 1)
        thruster_PWM_offset: [-28, -28, -28, -28, -28, -28, -28, -28] # Offset IN PWM -400 to 400 # Offset moves where the thrust is at rest
        thruster_PWM_min: [1100, 1100, 1100, 1100, 1100, 1100, 1100, 1100] # Minimum PWM value, Recomended: [1100, 1100, 1100, 1100, 1100, 1100, 1100, 1100]
        thruster_PWM_max: [1900, 1900, 1900, 1900, 1900, 1900, 1900, 1900] # Maximum PWM value, Recomended: [1900, 1900, 1900, 1900, 1900, 1900, 1900, 1900]
    
    internal_status:
      power_sense_module_read_rate: 5.0 # Readings/second, Recomended: 5.0
      voltage_min: 14.5 # [V], Recomended: 14.5
      voltage_max: 16.8 # [V], Recomended: 16.8
      power_sense_module_warning_rate: 0.1 # Warnings/second in case something goes bad you have a warning, Recomended: 0.1
      
      pressure_read_rate: 1.0 # Readings/second, Recomended: 1.0
      pressure_critical_level: 1000.0 # [hPa] If the pressure is over this amount there might be a leakage, Recomended: <1013.25
      pressure_warning_rate: 0.1 # Warnings/second in case something goes bad you have a warning, Recomended: 0.1
      
      temperature_read_rate: 0.1 # Readings/second, Recomended: 0.1
      temperature_critical_level: 90.0 # [*C] If temperature is over this amount the electrical housing might be overheating, Recomended: 90.0
      temperature_warning_rate: 0.1 # Warnings/second in case something goes bad you have a warning, Recomended: 0.1
      

      

