name: Bandit Security Scan

on: [pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install bandit
        run: |
          python -m pip install bandit[toml]

      - name: Run bandit scan
        run: |
          bandit -c pyproject.toml -r . --severity-level medium
