name: Black Code Formatter Check

on: [pull_request]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install black
        run: |
          python -m pip install black

      - name: Run black
        run: |
          black --check .
