on: push
jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - uses: ika-rwth-aachen/docker-ros@v1.6.1
        with:
          base-image: rwthika/ros2:humble
          command: ros2 launch auv_setup orca.launch.py
