name: Clang Tidy
# Build the ROS 2 workspace from clang tidy
on:
  pull_request:
jobs:
  source-build:
    uses: vortexntnu/vortex-ci/.github/workflows/reusable-clang-tidy.yaml@feat/clang-tidy-ros2
    with:
      ros_distro: 'humble'
      os_name: 'ubuntu-22.04'
      ref: ${{ github.ref_name }}
      vcs_repo_file_url: 'https://raw.githubusercontent.com/vortexntnu/vortex-auv/main/ros2.repos'
