name: flake8 Lint

on:
    workflow_run:
        workflows: ["Format python code"]
        types:
            - completed
jobs:
    flake8-lint:
        runs-on: ubuntu-22.04
        name: Lint
        steps:
            - name: check out source repo
              uses: actions/checkout@v3

            - name: Set up Python environment
              uses: actions/setup-python@v4
              with:
                python-version: 3

            - name: Install flake8
              run: pip --disable-pip-version-check install flake8

            - name: Lint with flake8
              run: flake8 --count
              continue-on-error: false