name: isort Import Sorting Check

on: [pull_request]

jobs:
  isort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install isort
        run: |
          python -m pip install isort

      - name: Run isort
        run: |
          isort --check .
