name: isort_black_pylint

on: [pull_request]

jobs:
  isort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run isort to sort imports
        uses: isort/isort-action@v1

      - name: Commit isort changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Isort Robot
          author_email: isort-robot@example.com
          message: 'Committing isort changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  black:
    runs-on: ubuntu-latest
    needs: isort  

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      - name: Commit black-format changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Black Robot
          author_email: black-robot@example.com
          message: 'Committing black-format changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pylint:
    runs-on: ubuntu-latest
    needs: black
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

