name: mypy

on: [pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install mypy
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install mypy

      - name: Run mypy type checking
        run: |
          mypy . --explicit-package-bases
