name: Mypy Type Checker

on: [pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install mypy
        run: |
          python -m pip install mypy

      - name: Run mypy
        run: |
          mypy . --explicit-package-bases
