name: Run autopep8 Formatter

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v2

    # Step 2: Set up Python environment (since autopep8 is a Python tool)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install autopep8
    - name: Install autopep8
      run: pip install autopep8

    # Step 4: Run autopep8 formatter with aggressive mode on all files recursively
    - name: Run autopep8
      run: autopep8 --in-place --recursive --aggressive --aggressive .

    # Step 5: Commit changes made by autopep8
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: 'Autopep8 Robot'
        author_email: 'robot@example.com'
        message: 'Committing autopep8 formatting changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
