name: Pylint Code Linter

on: [pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pylint
        run: |
          python -m pip install pylint

      - name: Run pylint
        run: |
          pylint .
